dir_day = '/opt/fintools-ib/data/day'
dir_quote = '/opt/fintools-ib/data/quotes'
file_conids = '/opt/fintools-ib/data/conids.json'
url_cheap_symbols = 'http://5.152.176.191/lt/3'
url_nasdaq_list = 'ftp://ftp.nasdaqtrader.com/symboldirectory/nasdaqlisted.txt'
